[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"
[features]
resolution = true
skip-lint = false
[programs.localnet]
vowpool = "A2JT4HUJYEd3BL5xPXRiaXjvoFSMetY8zvLEPmRAxXPf"
[programs.devnet]
vowpool = "A2JT4HUJYEd3BL5xPXRiaXjvoFSMetY8zvLEPmRAxXPf"
[provider]
cluster = "Localnet"
wallet = ".tools/keys/local-payer.json"
[scripts]
test = "VOWPOOL_RPC_SMOKE=1 bun run test:program"
[[test.genesis]]
address = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgMQHGhGusJA"
program = "target/deploy/mock_forwarder.so"
[workspace]
members = ["programs/vowpool"]
