'use client';
import {useState} from 'react';
import {draftSchema,type CommitmentDraft,type VerificationMode} from '../../../packages/shared/src/schema';
import {singaporeLocalToUtc,displayTime} from '../../../packages/shared/src/time';
import {type GroupView} from '../lib/chain';
import type {AiDraft} from '../lib/ai';
export const modeLabels:Record<VerificationMode,string>={single:'A · One appointed verifier',multiple:'B · All appointed verifiers',group:'C · Any other group member',github:'D · GitHub PR verification'};
const toLocal=(seconds:number)=>new Date(seconds*1000+8*3600000).toISOString().slice(0,16);
export default function CreateForm({group,owner,busy,onCreate,onClose}:{group:GroupView;owner:string;busy:boolean;onCreate:(d:CommitmentDraft)=>Promise<void>;onClose:()=>void}){
 const [goal,setGoal]=useState(''),[criteria,setCriteria]=useState(''),[stake,setStake]=useState('1'),[consequence,setConsequence]=useState(''),[mode,setMode]=useState<VerificationMode>('single'),[reviewers,setReviewers]=useState<string[]>([]);
 const [goalDate,setGoalDate]=useState(()=>toLocal(Math.floor(Date.now()/1000)+3600)),[reviewDate,setReviewDate]=useState(()=>toLocal(Math.floor(Date.now()/1000)+7200));
 const [githubOwner,setGithubOwner]=useState(''),[repo,setRepo]=useState(''),[pr,setPr]=useState(''),[branch,setBranch]=useState('main');
 const [aiGoal,setAiGoal]=useState(''),[aiBusy,setAiBusy]=useState(false),[aiMessage,setAiMessage]=useState(''),[error,setError]=useState(''),[confirmed,setConfirmed]=useState<CommitmentDraft|null>(null);
 async function draftWithAi(){setAiBusy(true);setAiMessage('');try{const response=await fetch('/api/configure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:aiGoal,mode,nowSingapore:new Date().toLocaleString('en-SG',{timeZone:'Asia/Singapore'})})});const result=await response.json();if(!response.ok)throw new Error(result.error);const a=result as AiDraft;const d=a.draft;if(d.goal!==null)setGoal(d.goal);if(d.criteria!==null)setCriteria(d.criteria);if(d.owner!==null)setGithubOwner(d.owner);if(d.repo!==null)setRepo(d.repo);if(d.pr!==null)setPr(String(d.pr));if(d.targetBranch!==null)setBranch(d.targetBranch);if(d.goalDeadline!==null)setGoalDate(toLocal(d.goalDeadline));if(d.reviewDeadline!==null)setReviewDate(toLocal(d.reviewDeadline));setAiMessage(`${a.explanation}${a.missingFields.length?' Please supply: '+a.missingFields.join(', '):''}`);}catch(e){setAiMessage(e instanceof Error?e.message:'AI unavailable. Use manual entry.');}finally{setAiBusy(false);}}
 function review(event:React.FormEvent){event.preventDefault();setError('');try{const d=draftSchema.parse({owner,goal,criteria,stake,tokenDecimals:group.decimals,consequence:consequence||undefined,mode,reviewers:mode==='single'||mode==='multiple'?reviewers:[],goalDeadline:singaporeLocalToUtc(goalDate),reviewDeadline:singaporeLocalToUtc(reviewDate),github:mode==='github'?{owner:githubOwner,repo,pr:Number(pr),targetBranch:branch,policyVersion:1}:undefined});if(d.goalDeadline<=Math.floor(Date.now()/1000))throw new Error('Goal deadline must be in the future');if(mode==='github'&&!group.automatedReady)throw new Error('CRE policy is not yet bound to this group. Save your draft and use a peer mode for now.');setConfirmed(d);}catch(e){setError(e instanceof Error?e.message:'Check the form');}}
 return <section className="panel creation" aria-label="Create commitment"><div className="section-head"><div><p className="eyebrow">MAKE IT CONCRETE</p><h1>A promise with a plan.</h1></div><button className="quiet" onClick={onClose} disabled={busy}>Close</button></div>
 {confirmed?<div><h3>Confirm the frozen terms</h3><p>{confirmed.goal}</p><p className="muted">{confirmed.criteria}</p><dl className="facts"><div><dt>Stake</dt><dd>{confirmed.stake} test tokens</dd></div><div><dt>Verification</dt><dd>{modeLabels[confirmed.mode]}</dd></div><div><dt>Goal deadline</dt><dd>{displayTime(confirmed.goalDeadline)} SGT</dd></div><div><dt>Review cutoff</dt><dd>{displayTime(confirmed.reviewDeadline)} SGT</dd></div></dl>{confirmed.github?<p>PR #{confirmed.github.pr} in {confirmed.github.owner}/{confirmed.github.repo}, merged into <strong>{confirmed.github.targetBranch}</strong> after activation and by the goal deadline.</p>:<p>All appointed reviewers must acknowledge before activation. Missing required approval by the review cutoff forfeits the stake to the group.</p>}<p className="notice">These terms cannot be edited. Creation records the terms; locking the stake is a separate wallet action.</p><div className="button-row"><button disabled={busy} onClick={()=>setConfirmed(null)} className="quiet">Edit terms</button><button disabled={busy} onClick={()=>onCreate(confirmed)}>{busy?'Waiting for wallet…':'Create commitment'}</button></div></div>:<form onSubmit={review}>
 <label>What will you do?<input required value={goal} onChange={e=>setGoal(e.target.value)} maxLength={500} placeholder="Ship the sign-in flow"/></label><label>What counts as complete?<textarea required value={criteria} onChange={e=>setCriteria(e.target.value)} maxLength={2000} placeholder="State the exact result your verifier will review."/></label>
 <label>Verification mode<select aria-label="Verification mode" value={mode} onChange={e=>{setMode(e.target.value as VerificationMode);setReviewers([]);}}>{Object.entries(modeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <details className="ai-box"><summary>Help me draft this with AI</summary><label>Describe the goal and known details<textarea value={aiGoal} onChange={e=>setAiGoal(e.target.value)} placeholder="Merge PR #12 in my-org/my-repo into main by Friday at 6pm…" maxLength={4000}/></label><button type="button" className="quiet" disabled={aiBusy||!aiGoal.trim()} onClick={draftWithAi}>{aiBusy?'Drafting…':'Draft terms'}</button>{aiMessage?<p role="status" className="muted">{aiMessage}</p>:null}<small>Review and edit every field. AI drafts configuration; completion is verified by the selected rules.</small></details>

 <div className="field-grid"><label>Stake · test tokens<input required inputMode="decimal" value={stake} onChange={e=>setStake(e.target.value)} pattern="(?:0|[1-9][0-9]*)(?:\.[0-9]+)?"/></label><label>Physical consequence · optional<input value={consequence} onChange={e=>setConsequence(e.target.value)} maxLength={2000} placeholder="Buy coffee for the group"/></label><label>Goal deadline · Singapore<input type="datetime-local" required value={goalDate} onChange={e=>setGoalDate(e.target.value)}/></label><label>Review cutoff · Singapore<input type="datetime-local" required value={reviewDate} onChange={e=>setReviewDate(e.target.value)}/></label></div>
 {['single','multiple'].includes(mode)?<fieldset><legend>Appointed verifiers</legend>{group.roster.filter(r=>r!==owner).map(r=><label className="check" key={r}><input type={mode==='single'?'radio':'checkbox'} name="verifier" checked={reviewers.includes(r)} onChange={e=>setReviewers(mode==='single'?[r]:e.target.checked?[...reviewers,r]:reviewers.filter(x=>x!==r))}/><span>{r}</span></label>)}</fieldset>:null}
 {mode==='github'?<><div className="field-grid"><label>GitHub owner<input required value={githubOwner} onChange={e=>setGithubOwner(e.target.value)}/></label><label>Public repository<input required value={repo} onChange={e=>setRepo(e.target.value)}/></label><label>Exact PR number<input required inputMode="numeric" pattern="[1-9][0-9]*" value={pr} onChange={e=>setPr(e.target.value)}/></label><label>Target branch<input required value={branch} onChange={e=>setBranch(e.target.value)}/></label></div><p className="notice">API outages stay pending. If verification remains inconclusive 48 hours after the review cutoff, the stake becomes an unresolved refund. This is separate from verified success.</p>{!group.automatedReady?<p className="error">Automated activation is unavailable until an authorized CRE policy is bound to the group.</p>:null}</>:<p className="notice">Missing required peer approval by the review cutoff means forfeiture. Verifier acknowledgment and completion approval are separate actions.</p>}
 {error?<p className="error" role="alert">{error}</p>:null}<button type="submit" disabled={busy}>Review frozen terms →</button></form>}
 </section>;
}
