'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {useConnection,useWallet} from '@solana/wallet-adapter-react';
import {Transaction} from '@solana/web3.js';
import {formatTokenAmount,parseTokenAmount} from '../../../packages/shared/src/amount';
import {displayTime} from '../../../packages/shared/src/time';
import type {CommitmentDraft} from '../../../packages/shared/src/schema';
import {groupAddress,preparedGroup,readGroup,readCommitments,PROGRAM_ID,type GroupView,type CommitmentView} from '../lib/chain';
import {availableActions,initializeGroupAction,createAction,lifecycleAction,withdrawAction,type LifecycleAction} from '../lib/actions';
import {needsReview,commitmentStatus} from '../lib/presentation';
import {sendAndConfirm,type TransactionPhase} from '../lib/transactions';
import CreateForm from './create-form';
import {PactHeader,BalanceSummary,CommitmentList,PactFooter,type Section,type CommitmentRowData} from './pact-ui';
import Detail,{short,accountLink,exportTerms} from './detail';
const WalletButton=dynamic(()=>import('@solana/wallet-adapter-react-ui').then(m=>m.WalletMultiButton),{ssr:false});
type TermsRecord={status:string;terms?:CommitmentDraft};
export default function Dashboard(){
 const {connection}=useConnection(),wallet=useWallet(),address=wallet.publicKey?.toBase58();const context=`${address||''}:${connection.rpcEndpoint}`,contextRef=useRef(context);contextRef.current=context;
 const [group,setGroup]=useState<GroupView|null>(null),[commitments,setCommitments]=useState<CommitmentView[]>([]),[readWarnings,setReadWarnings]=useState<string[]>([]),[terms,setTerms]=useState<Record<string,TermsRecord>>({}),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [tab,setTab]=useState<Section>('commitments'),[refundsOnly,setRefundsOnly]=useState(false),[creation,setCreation]=useState(false),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),busyRef=useRef(false),[phase,setPhase]=useState<TransactionPhase|null>(null),[signature,setSignature]=useState(''),[notice,setNotice]=useState('');
 const [outbox,setOutbox]=useState<{address:string;terms:CommitmentDraft}|null>(null),[withdraw,setWithdraw]=useState(''),[now,setNow]=useState(()=>Math.floor(Date.now()/1000)),generation=useRef(0);
 const reload=useCallback(async(minContextSlot?:number)=>{if(!groupAddress)return false;const run=++generation.current;setLoading(true);setError('');const unreadable:string[]=[];try{const [g,cs]=await Promise.all([readGroup(connection,groupAddress,minContextSlot),readCommitments(connection,groupAddress,minContextSlot,a=>unreadable.push(a))]);if(generation.current!==run)return false;setGroup(g);setCommitments(cs);setReadWarnings(unreadable);const metadata=await Promise.all(cs.map(async c=>{try{const r=await fetch(`/api/metadata?address=${c.address}`);const v=await r.json();return [c.address,r.ok?v:{status:'unavailable'}] as const;}catch{return [c.address,{status:'unavailable'}] as const;}}));if(generation.current===run)setTerms(Object.fromEntries(metadata));return generation.current===run;}catch(e){if(generation.current===run)setError(e instanceof Error?e.message:'Could not read confirmed accounts');return false;}finally{if(generation.current===run)setLoading(false);}},[connection]);
 useEffect(()=>{void reload();return()=>{generation.current++;};},[reload]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Math.floor(Date.now()/1000)),15000);return()=>clearInterval(timer);},[]);
 async function transact(build:()=>Promise<Transaction>){if(busyRef.current)throw new Error('A transaction is already in progress');busyRef.current=true;setBusy(true);setError('');setNotice('');setSignature('');setPhase(null);const initial=contextRef.current;try{const tx=await build();if(contextRef.current!==initial)throw new Error('Wallet or network changed');const result=await sendAndConfirm(tx,wallet,connection,{context:()=>contextRef.current,onPhase:(p,s)=>{setPhase(p);if(s)setSignature(s);}});const refreshed=await reload(result.confirmedSlot);if(contextRef.current===initial)setNotice(refreshed?'Transaction confirmed. Showing the latest chain state.':'Transaction confirmed. Account refresh failed; refresh before acting again.');else setNotice('Transaction confirmed for the previous wallet. Review its receipt.');return result;}catch(e){setError(e instanceof Error?e.message:'Transaction failed');throw e;}finally{busyRef.current=false;setBusy(false);}}
 async function create(draft:CommitmentDraft){if(!group)return;const random=new Uint32Array(2);crypto.getRandomValues(random);const nonce=(BigInt(random[0])<<32n)|BigInt(random[1]);let createdAddress='';try{await transact(async()=>{const built=await createAction(connection,group,draft,nonce);createdAddress=built.address;return built.transaction;});setCreation(false);setSelected(createdAddress);const record={address:createdAddress,terms:draft};setOutbox(record);await saveTerms(record);}catch{}}
 async function saveTerms(record:{address:string;terms:CommitmentDraft}){try{const r=await fetch('/api/metadata',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});const v=await r.json();if(!r.ok)throw new Error(v.error);setOutbox(null);await reload();}catch(e){setNotice(`The commitment is onchain. Terms could not be saved: ${e instanceof Error?e.message:'storage unavailable'}. Export them and retry saving.`);}}
 async function act(c:CommitmentView,a:LifecycleAction){if(!group||!address)return;try{await transact(()=>lifecycleAction(connection,group,c,address,a));}catch{}}
 async function spend(event:React.FormEvent){event.preventDefault();if(!group||!address)return;try{const amount=parseTokenAmount(withdraw,group.decimals);if(amount<=0n||amount>group.pool)throw new Error('Choose an amount within the available communal budget');await transact(()=>withdrawAction(connection,group,address,amount));setWithdraw('');}catch(e){setError(e instanceof Error?e.message:'Withdrawal failed');}}
 const detail=commitments.find(c=>c.address===selected),member=!!address&&!!group?.roster.includes(address);
 const own=commitments.filter(c=>c.owner===address),active=own.filter(c=>c.status==='active').reduce((s,c)=>s+c.amount,0n),refundable=own.filter(c=>['succeeded','unresolved'].includes(c.status)&&!c.refundReleased).reduce((s,c)=>s+c.amount,0n);
 const reviews=commitments.filter(c=>group&&needsReview(c,group,address,now));
 const visible=tab==='reviews'?reviews:refundsOnly?own.filter(c=>['succeeded','unresolved'].includes(c.status)&&!c.refundReleased):own;
 function navigate(section:Section){setTab(section);setCreation(false);setSelected(null);setRefundsOnly(false);}
 function openCommitment(id:string){setSelected(id);setCreation(false);window.scrollTo({top:0,behavior:'smooth'});}
 const amount=(n:bigint)=>formatTokenAmount(n,group?.decimals??6);
 function rowAction(id:string){const c=visible.find(c=>c.address===id);if(c&&group&&availableActions(c,group,address,now).includes('releaseRefund'))void act(c,'releaseRefund');else openCommitment(id);}
 const rows:CommitmentRowData[]=visible.map(c=>{
  const d=terms[c.address],hasTerms=d?.status==='verified'&&!!d.terms;
  const actions=group?availableActions(c,group,address,now):[];
  const expired=c.status==='active'&&c.mode!=='github'&&now>c.reviewDeadline;
  const refundable=['succeeded','unresolved'].includes(c.status)&&!c.refundReleased;
  const status=commitmentStatus(c,now);
  const action=actions.includes('acknowledge')?'Review invitation':actions.includes('activate')?'Lock stake':actions.includes('approve')?'Review evidence':refundable&&actions.includes('releaseRefund')?'Release refund':undefined;
  return {id:c.address,goal:hasTerms?d.terms!.goal:'Terms unavailable',summary:hasTerms?`${amount(c.amount)} test tokens · ${c.status==='active'?`${c.mode==='github'?'Due':'Review by'} ${displayTime(c.mode==='github'?c.goalDeadline:c.reviewDeadline)} SGT`:c.owner===address?'Your commitment':short(c.owner)}`:`${amount(c.amount)} test tokens · Original terms need verification.`,status,tone:expired||c.status==='failed'?'attention':c.status==='succeeded'?'success':c.status==='active'&&c.mode!=='github'?'pending':'neutral',action};
 });
 const focused=!!(creation&&group&&address)||!!detail;
 return <main className="shell"><PactHeader section={tab} onNavigate={navigate} reviewCount={reviews.length} wallet={<WalletButton/>}/>
 {!focused?<><section className="hero"><div><p className="eyebrow">YOUR ACCOUNTABILITY CIRCLE</p><h1>{tab==='reviews'?'A little follow-through.':tab==='pool'?'Our shared pool.':'Keep your word.'}</h1></div>{tab==='commitments'?<button disabled={!member||busy} onClick={()=>{setCreation(true);setSelected(null);}}>+ Make a commitment</button>:null}</section>
 {tab==='commitments'?<BalanceSummary active={group&&address&&!readWarnings.length?amount(active):'—'} refundable={group&&address&&!readWarnings.length?amount(refundable):'—'} pool={group?amount(group.pool):'—'} onPool={()=>navigate('pool')} onRefunds={()=>setRefundsOnly(true)}/>:null}</>:null}
 {preparedGroup&&!group?<section className="panel setup"><h2>Initialize your fixed group</h2><p>The founder signs one transaction to freeze this roster, mint, treasury destination and CRE policy.</p><p>Founder: {short(preparedGroup.founder)} · {preparedGroup.roster.length} members · Test tokens only</p><p>Mint: <a href={accountLink(preparedGroup.mint)} target="_blank" rel="noreferrer">{short(preparedGroup.mint)} ↗</a></p><p>Roster: {preparedGroup.roster.map(short).join(', ')}</p><p>Treasurer: {short(preparedGroup.treasurer)} · Treasury recipient: {short(preparedGroup.treasuryRecipient)}</p><details><summary>Review frozen CRE policy</summary><pre style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{JSON.stringify(preparedGroup.policy,null,2)}</pre></details>{preparedGroup.developmentFixture?<p className="notice">DEVELOPMENT FIXTURE · Mock forwarder · No live DON authentication</p>:null}<button disabled={busy||loading||address!==preparedGroup.founder} onClick={()=>{if(address)void transact(()=>initializeGroupAction(connection,preparedGroup,address)).catch(()=>{});}}>Initialize fixed group</button>{address!==preparedGroup.founder?<p>Connect the member founder wallet to initialize.</p>:null}</section>:null}
 {group?.policy.forwarder.toBase58()==='7kuEAA3mSC1Tz8gQjnvH7bKFda9xSPRRin9SZbH49cNK'?<p className="notice">DEVELOPMENT FIXTURE · Mock CRE forwarder · Live DON authentication unverified</p>:null}
 {readWarnings.length?<section className="notice" role="status"><strong>Some commitment records are unavailable</strong><p>Wallet stake and refund totals may be incomplete. Other readable commitments remain available. Refresh or inspect the affected chain accounts:</p><p>{readWarnings.map(key=><a key={key} className="member" href={accountLink(key)} target="_blank" rel="noreferrer">{short(key)} ↗</a>)}</p></section>:null}
 {phase||notice||error?<section className={`transaction-notice ${error?'has-error':''}`} aria-live="polite"><strong>{phase?phase.charAt(0).toUpperCase()+phase.slice(1):error?'Action needs attention':'Update'}</strong>{notice?<p>{notice}</p>:null}{error?<p>{error}</p>:null}{signature?<a href={`https://explorer.solana.com/tx/${signature}?cluster=devnet`} target="_blank" rel="noreferrer">View transaction receipt ↗</a>:null}{phase==='failed'&&signature?<p>Check the receipt before retrying; confirmation may be unavailable.</p>:null}</section>:null}
 {outbox?<section className="notice"><strong>Save your original terms</strong><p>The chain transaction succeeded. Keep an export while metadata storage is retried.</p><div className="button-row"><button className="quiet" onClick={()=>exportTerms(outbox.terms,outbox.address)}>Export terms ↓</button><button disabled={busy} onClick={()=>saveTerms(outbox)}>Retry metadata save</button></div></section>:null}
 {creation&&group&&address?<CreateForm key={address} group={group} owner={address} busy={busy} onCreate={create} onClose={()=>setCreation(false)}/>:null}
 {detail&&group?<Detail key={detail.address} commitment={detail} group={group} walletAddress={address} busy={busy} now={now} onAction={act} onClose={()=>setSelected(null)}/>:null}
 {!focused&&tab!=='pool'?<section className="commitments" aria-label={tab==='reviews'?'Reviews':'Your commitments'}>
 <div className="list-tools">{refundsOnly?<button className="text-button" onClick={()=>setRefundsOnly(false)}>← All commitments</button>:<span/>}<button className="text-button refresh" disabled={loading||busy||!groupAddress} onClick={()=>reload()}>{loading?'Refreshing…':'Refresh'}</button></div>
 {!groupAddress?<div className="empty"><h2>Your circle is taking shape.</h2><p>The group roster and test-token vault still need to be configured.</p><details className="setup-details"><summary>Setup details</summary><p>No balances or commitments are simulated.</p><a href={accountLink(PROGRAM_ID.toBase58())} target="_blank" rel="noreferrer">View program on Devnet ↗</a><p>Automated creation requires an authorized CRE policy binding.</p></details></div>:loading&&!group?<p className="empty" role="status">Reading confirmed program accounts…</p>:visible.length?<CommitmentList rows={rows} busy={busy} onOpen={openCommitment} onAction={rowAction}/>:<div className="empty"><h2>{!address?'Make yourself at home.':tab==='reviews'?'You’re all caught up.':refundsOnly?'No refunds waiting.':'Your next promise starts here.'}</h2><p>{!address?'Connect your wallet to see your commitments and reviews.':tab==='reviews'?'Reviewer invitations and completion reviews will appear here.':refundsOnly?'Recorded refunds will appear here when available.':'A clear goal is a good place to start.'}</p>{address&&!member&&group?<p>This wallet is not in the fixed group roster.</p>:null}</div>}
 </section>:null}
 {!focused&&tab==='pool'?<section className="pool-view"><div className="pool-heading"><img src="/ripple-mark.png" alt="" width="58" height="58"/><div><p className="eyebrow">AVAILABLE TO THE GROUP</p><h2>{group?amount(group.pool):'—'} <span>test tokens</span></h2></div></div><p className="muted">Forfeited stakes support the circle. Locked stakes and unpaid refunds stay separate.</p><details className="group-activity"><summary>Group commitments{commitments.length?` · ${commitments.length}`:''}</summary><ul className="activity-list">{commitments.map(c=><li key={c.address}><button className="text-button" onClick={()=>openCommitment(c.address)}>{terms[c.address]?.status==='verified'?terms[c.address].terms?.goal:'Terms unavailable'}</button><span>{short(c.owner)}</span></li>)}</ul>{!commitments.length?<p className="muted">No group commitments to show.</p>:null}</details></section>:null}
 {!focused&&tab==='pool'&&group?<details className="panel group-details"><summary>Group rules & public accounts</summary><p>One fixed mint and roster. Active stakes, unpaid refunds and available budget are tracked separately.</p><p>{group.roster.map(r=><a key={r} className="member" href={accountLink(r)} target="_blank" rel="noreferrer">{short(r)}{r===group.treasurer?' · treasurer':''}</a>)}</p><div className="button-row"><a href={accountLink(group.mint)} target="_blank" rel="noreferrer">Test mint ↗</a><a href={accountLink(group.vault)} target="_blank" rel="noreferrer">Escrow vault ↗</a><a href={accountLink(group.address)} target="_blank" rel="noreferrer">Group account ↗</a></div>{group.treasurer===address?<form onSubmit={spend}><label>Spend available communal budget · test tokens<input value={withdraw} onChange={e=>setWithdraw(e.target.value)} inputMode="decimal" required/></label><p className="muted">Destination is fixed: {short(group.treasuryRecipient)}. Active escrow and unpaid refunds remain protected.</p><button disabled={busy||group.pool===0n}>Withdraw to fixed treasury recipient</button></form>:null}</details>:null}
 <PactFooter/></main>;
}
