'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {useConnection,useWallet} from '@solana/wallet-adapter-react';
import {Transaction} from '@solana/web3.js';
import {formatTokenAmount,parseTokenAmount} from '../../../packages/shared/src/amount';
import {displayTime} from '../../../packages/shared/src/time';
import type {CommitmentDraft} from '../../../packages/shared/src/schema';
import {groupAddress,preparedGroup,readGroup,readCommitments,PROGRAM_ID,type GroupView,type CommitmentView} from '../lib/chain';
import {availableActions,initializeGroupAction,createAction,lifecycleAction,withdrawAction,type LifecycleAction} from '../lib/actions';
import {sendAndConfirm,type TransactionPhase} from '../lib/transactions';
import CreateForm,{modeLabels} from './create-form';
import Detail,{short,accountLink,exportTerms} from './detail';
const WalletButton=dynamic(()=>import('@solana/wallet-adapter-react-ui').then(m=>m.WalletMultiButton),{ssr:false});
type TermsRecord={status:string;terms?:CommitmentDraft};
export default function Dashboard(){
 const {connection}=useConnection(),wallet=useWallet(),address=wallet.publicKey?.toBase58();const context=`${address||''}:${connection.rpcEndpoint}`,contextRef=useRef(context);contextRef.current=context;
 const [group,setGroup]=useState<GroupView|null>(null),[commitments,setCommitments]=useState<CommitmentView[]>([]),[terms,setTerms]=useState<Record<string,TermsRecord>>({}),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [tab,setTab]=useState('My commitments'),[creation,setCreation]=useState(false),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),busyRef=useRef(false),[phase,setPhase]=useState<TransactionPhase|null>(null),[signature,setSignature]=useState(''),[notice,setNotice]=useState('');
 const [outbox,setOutbox]=useState<{address:string;terms:CommitmentDraft}|null>(null),[withdraw,setWithdraw]=useState(''),[now,setNow]=useState(()=>Math.floor(Date.now()/1000)),generation=useRef(0);
 const reload=useCallback(async(minContextSlot?:number)=>{if(!groupAddress)return false;const run=++generation.current;setLoading(true);setError('');try{const [g,cs]=await Promise.all([readGroup(connection,groupAddress,minContextSlot),readCommitments(connection,groupAddress,minContextSlot)]);if(generation.current!==run)return false;setGroup(g);setCommitments(cs);const metadata=await Promise.all(cs.map(async c=>{try{const r=await fetch(`/api/metadata?address=${c.address}`);const v=await r.json();return [c.address,r.ok?v:{status:'unavailable'}] as const;}catch{return [c.address,{status:'unavailable'}] as const;}}));if(generation.current===run)setTerms(Object.fromEntries(metadata));return generation.current===run;}catch(e){if(generation.current===run)setError(e instanceof Error?e.message:'Could not read confirmed accounts');return false;}finally{if(generation.current===run)setLoading(false);}},[connection]);
 useEffect(()=>{void reload();return()=>{generation.current++;};},[reload]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Math.floor(Date.now()/1000)),15000);return()=>clearInterval(timer);},[]);
 async function transact(build:()=>Promise<Transaction>){if(busyRef.current)throw new Error('A transaction is already in progress');busyRef.current=true;setBusy(true);setError('');setNotice('');setSignature('');setPhase(null);const initial=contextRef.current;try{const tx=await build();if(contextRef.current!==initial)throw new Error('Wallet or network changed');const result=await sendAndConfirm(tx,wallet,connection,{context:()=>contextRef.current,onPhase:(p,s)=>{setPhase(p);if(s)setSignature(s);}});const refreshed=await reload(result.confirmedSlot);if(contextRef.current===initial)setNotice(refreshed?'Transaction confirmed. Showing the latest chain state.':'Transaction confirmed. Account refresh failed; refresh before acting again.');else setNotice('Transaction confirmed for the previous wallet. Review its receipt.');return result;}catch(e){setError(e instanceof Error?e.message:'Transaction failed');throw e;}finally{busyRef.current=false;setBusy(false);}}
 async function create(draft:CommitmentDraft){if(!group)return;const random=new Uint32Array(2);crypto.getRandomValues(random);const nonce=(BigInt(random[0])<<32n)|BigInt(random[1]);let createdAddress='';try{await transact(async()=>{const built=await createAction(connection,group,draft,nonce);createdAddress=built.address;return built.transaction;});setCreation(false);setSelected(createdAddress);const record={address:createdAddress,terms:draft};setOutbox(record);await saveTerms(record);}catch{}}
 async function saveTerms(record:{address:string;terms:CommitmentDraft}){try{const r=await fetch('/api/metadata',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});const v=await r.json();if(!r.ok)throw new Error(v.error);setOutbox(null);await reload();}catch(e){setNotice(`The commitment is onchain. Terms could not be saved: ${e instanceof Error?e.message:'storage unavailable'}. Export them and retry saving.`);}}
 async function act(c:CommitmentView,a:LifecycleAction){if(!group||!address)return;try{await transact(()=>lifecycleAction(connection,group,c,address,a));}catch{}}
 async function spend(event:React.FormEvent){event.preventDefault();if(!group||!address)return;try{const amount=parseTokenAmount(withdraw,group.decimals);if(amount<=0n||amount>group.pool)throw new Error('Choose an amount within the available communal budget');await transact(()=>withdrawAction(connection,group,address,amount));setWithdraw('');}catch(e){setError(e instanceof Error?e.message:'Withdrawal failed');}}
 const detail=commitments.find(c=>c.address===selected),member=!!address&&!!group?.roster.includes(address);
 const own=commitments.filter(c=>c.owner===address),active=own.filter(c=>c.status==='active').reduce((s,c)=>s+c.amount,0n),refundable=own.filter(c=>['succeeded','unresolved'].includes(c.status)&&!c.refundReleased).reduce((s,c)=>s+c.amount,0n);
 const visible=tab==='My commitments'?own:tab==='Needs my action'?commitments.filter(c=>group&&availableActions(c,group,address,now).length>0):commitments;
 const amount=(n:bigint)=>formatTokenAmount(n,group?.decimals??6);
 return <main className="shell"><header><a className="brand" href="/" aria-label="VowPool home"><span className="brand-mark">v</span>vowpool<span className="beta">DEVNET</span></a><WalletButton/></header>
 <section className="hero"><div><p className="eyebrow">THE THINGS WE SAY WE’LL DO.</p><h1>Make a promise.<br/><span>Keep it together.</span></h1><p>A shared space for real commitments, clear rules<br className="desktop-break"/> and a little skin in the game.</p></div><div className="hero-note"><span className="orbit">↗</span><p>Individual follow-through.<br/>Collective momentum.</p><small>Solana + Chainlink CRE</small></div></section>
 <div className="group-bar"><div><span className="dot"/><strong>Accountability group</strong><span className="muted">{group?`${group.roster.length} fixed members`:'Setup in progress'}</span></div><span className="test-label">Solana Devnet · test tokens only</span></div>
 {!groupAddress?<section className="panel setup"><h2>The program is deployed. The group is next.</h2><p>Connect member wallets after the fixed roster, mint and vault are configured. No commitment or balance is being simulated here.</p><a href={accountLink(PROGRAM_ID.toBase58())} target="_blank" rel="noreferrer">View deployed program ↗</a><p className="muted">CRE live deployment access is not enabled for the current account. Automated creation requires an authorized policy binding.</p></section>:null}
 {preparedGroup&&!group?<section className="panel setup"><h2>Initialize your fixed group</h2><p>The founder signs one transaction to freeze this roster, mint, treasury destination and CRE policy.</p><p>Founder: {short(preparedGroup.founder)} · {preparedGroup.roster.length} members · Test tokens only</p><p>Mint: <a href={accountLink(preparedGroup.mint)} target="_blank" rel="noreferrer">{short(preparedGroup.mint)} ↗</a></p><p>Roster: {preparedGroup.roster.map(short).join(', ')}</p><p>Treasurer: {short(preparedGroup.treasurer)} · Treasury recipient: {short(preparedGroup.treasuryRecipient)}</p><details><summary>Review frozen CRE policy</summary><pre style={{overflowWrap:'anywhere',whiteSpace:'pre-wrap'}}>{JSON.stringify(preparedGroup.policy,null,2)}</pre></details>{preparedGroup.developmentFixture?<p className="notice">DEVELOPMENT FIXTURE · Mock forwarder · No live DON authentication</p>:null}<button disabled={busy||loading||address!==preparedGroup.founder} onClick={()=>{if(address)void transact(()=>initializeGroupAction(connection,preparedGroup,address)).catch(()=>{});}}>Initialize fixed group</button>{address!==preparedGroup.founder?<p>Connect the member founder wallet to initialize.</p>:null}</section>:null}
 {group?.policy.forwarder.toBase58()==='7kuEAA3mSC1Tz8gQjnvH7bKFda9xSPRRin9SZbH49cNK'?<p className="notice">DEVELOPMENT FIXTURE · Mock CRE forwarder · Live DON authentication unverified</p>:null}
 <section className="stats" aria-label="Confirmed balances"><div><p>COMMUNAL BUDGET</p><strong>{group?amount(group.pool):'—'}<small>test tokens</small></strong><span>Forfeited stakes, available to the group</span></div><div><p>YOUR ACTIVE STAKES</p><strong>{group&&address?amount(active):'—'}<small>test tokens</small></strong><span>Held until a recorded outcome</span></div><div><p>YOUR REFUNDS</p><strong>{group&&address?amount(refundable):'—'}<small>test tokens</small></strong><span>Recorded and ready to release</span></div></section>
 {phase||notice||error?<section className={`transaction-notice ${error?'has-error':''}`} aria-live="polite"><strong>{phase?phase.charAt(0).toUpperCase()+phase.slice(1):error?'Action needs attention':'Update'}</strong>{notice?<p>{notice}</p>:null}{error?<p>{error}</p>:null}{signature?<a href={`https://explorer.solana.com/tx/${signature}?cluster=devnet`} target="_blank" rel="noreferrer">View transaction receipt ↗</a>:null}{phase==='failed'&&signature?<p>Check the receipt before retrying; confirmation may be unavailable.</p>:null}</section>:null}
 {outbox?<section className="notice"><strong>Save your original terms</strong><p>The chain transaction succeeded. Keep an export while metadata storage is retried.</p><div className="button-row"><button className="quiet" onClick={()=>exportTerms(outbox.terms,outbox.address)}>Export terms ↓</button><button disabled={busy} onClick={()=>saveTerms(outbox)}>Retry metadata save</button></div></section>:null}
 {creation&&group&&address?<CreateForm key={address} group={group} owner={address} busy={busy} onCreate={create} onClose={()=>setCreation(false)}/>:null}
 {detail&&group?<Detail key={detail.address} commitment={detail} group={group} walletAddress={address} busy={busy} now={now} onAction={act} onClose={()=>setSelected(null)}/>:null}
 <section className="commitments"><div className="section-head"><div><p className="eyebrow">ONE STEP AT A TIME</p><h2>Your commitments</h2></div><div className="button-row"><button className="quiet" disabled={loading||busy||!groupAddress} onClick={()=>reload()}>{loading?'Refreshing…':'Refresh'}</button><button disabled={!member||busy} onClick={()=>{setCreation(true);setSelected(null);}}>+ New commitment</button></div></div>
 <nav className="tabs" aria-label="Commitment filters">{['My commitments','Needs my action','Group activity'].map(t=><button key={t} className={tab===t?'selected':''} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {loading&&!group?<p className="empty">Reading confirmed program accounts…</p>:visible.length?<div className="cards">{visible.map(c=>{const d=terms[c.address];const expired=c.status==='active'&&c.mode!=='github'&&now>c.reviewDeadline;return <button className="commitment-card" key={c.address} onClick={()=>{setSelected(c.address);setCreation(false);}}><div className="card-top"><span className={`status ${c.status}`}>{expired?'Expired · settlement pending':c.status==='unresolved'?'Unresolved refund':c.status}</span><span>{modeLabels[c.mode].split(' · ')[0]}</span></div><h3>{d?.status==='verified'?d.terms?.goal:'Terms unavailable'}</h3><p>{d?.status==='verified'?d.terms?.criteria:'Open the chain record and verify exported terms.'}</p><div className="card-foot"><strong>{amount(c.amount)} <small>test tokens</small></strong><span>Review {displayTime(c.reviewDeadline)}</span></div><small>{short(c.owner)} <span aria-hidden="true">→</span></small></button>;})}</div>:<div className="empty"><span className="empty-icon">↗</span><h3>{address?'Nothing here yet.':'Connect your wallet to begin.'}</h3><p>{address?'A clear goal is a good place to start.':'View the group, make a commitment, or accept a reviewer role.'}</p>{address&&!member&&group?<p>This wallet is not in the fixed group roster.</p>:null}</div>}
 </section>
 {group?<details className="panel group-details"><summary>Group rules & public accounts</summary><p>One fixed mint and roster. Active stakes, unpaid refunds and available budget are tracked separately.</p><p>{group.roster.map(r=><a key={r} className="member" href={accountLink(r)} target="_blank" rel="noreferrer">{short(r)}{r===group.treasurer?' · treasurer':''}</a>)}</p><div className="button-row"><a href={accountLink(group.mint)} target="_blank" rel="noreferrer">Test mint ↗</a><a href={accountLink(group.vault)} target="_blank" rel="noreferrer">Escrow vault ↗</a><a href={accountLink(group.address)} target="_blank" rel="noreferrer">Group account ↗</a></div>{group.treasurer===address?<form onSubmit={spend}><label>Spend available communal budget · test tokens<input value={withdraw} onChange={e=>setWithdraw(e.target.value)} inputMode="decimal" required/></label><p className="muted">Destination is fixed: {short(group.treasuryRecipient)}. Active escrow and unpaid refunds remain protected.</p><button disabled={busy||group.pool===0n}>Withdraw to fixed treasury recipient</button></form>:null}</details>:null}
 <footer><span>vowpool · Commit together.</span><span>Devnet demonstration · Upgrade authority retained</span></footer></main>;
}
