'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {useConnection,useWallet} from '@solana/wallet-adapter-react';
import {PublicKey,Transaction} from '@solana/web3.js';
import {getAccount,getAssociatedTokenAddressSync} from '@solana/spl-token';
import {formatTokenAmount,parseTokenAmount} from '../../../packages/shared/src/amount';
import {displayTime} from '../../../packages/shared/src/time';
import type {CommitmentDraft} from '../../../packages/shared/src/schema';
import type {PreparedGroup} from '../../../packages/shared/src/group-setup';
import {groupAddress,readGroup,readCommitments,type GroupView,type CommitmentView} from '../lib/chain';
import {readGroups,groupPda} from '../lib/groups';
import {claimDemoFunds} from '../lib/demo-client';
import {availableActions,initializeGroupAction,createAction,lifecycleAction,withdrawAction,type LifecycleAction} from '../lib/actions';
import {needsReview,commitmentStatus} from '../lib/presentation';
import {sendAndConfirm,type TransactionPhase} from '../lib/transactions';
import CreateForm from './create-form';
import SelectField from './select-field';
import GroupForm,{type DemoConfig} from './group-form';
import {PactHeader,BalanceSummary,CommitmentList,PactFooter,type Section,type CommitmentRowData} from './pact-ui';
import Detail,{short,accountLink,exportTerms} from './detail';
const WalletButton=dynamic(()=>import('@solana/wallet-adapter-react-ui').then(m=>m.WalletMultiButton),{ssr:false});
type TermsRecord={status:string;terms?:CommitmentDraft};
export default function Dashboard(){
 const {connection}=useConnection(),wallet=useWallet(),address=wallet.publicKey?.toBase58(),walletRef=useRef(wallet);walletRef.current=wallet;
 const [config,setConfig]=useState<DemoConfig|null>(null),[groups,setGroups]=useState<GroupView[]>([]),[activeGroup,setActiveGroup]=useState(''),activeRef=useRef('');
 const context=`${address||''}:${connection.rpcEndpoint}:${activeGroup}`,contextRef=useRef(context);contextRef.current=context;
 const [group,setGroup]=useState<GroupView|null>(null),[commitments,setCommitments]=useState<CommitmentView[]>([]),[readWarnings,setReadWarnings]=useState<string[]>([]),[terms,setTerms]=useState<Record<string,TermsRecord>>({}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[readError,setReadError]=useState('');
 const [tab,setTab]=useState<Section>('commitments'),[refundsOnly,setRefundsOnly]=useState(false),[creation,setCreation]=useState(false),[groupCreation,setGroupCreation]=useState(false),[selected,setSelected]=useState<string|null>(null),[busy,setBusy]=useState(false),busyRef=useRef(false),[phase,setPhase]=useState<TransactionPhase|null>(null),[signature,setSignature]=useState(''),[refundSignature,setRefundSignature]=useState(''),[notice,setNotice]=useState('');
 const [outbox,setOutbox]=useState<{address:string;terms:CommitmentDraft}|null>(null),[withdraw,setWithdraw]=useState(''),[now,setNow]=useState(()=>Math.floor(Date.now()/1000)),generation=useRef(0),refundRequests=useRef(new Set<string>());
 const selectGroup=useCallback((key:string)=>{activeRef.current=key;setActiveGroup(key);if(key){const url=new URL(window.location.href);url.searchParams.set('group',key);window.history.replaceState(null,'',url);}},[]);
 const reload=useCallback(async(minContextSlot?:number,target=activeRef.current)=>{
  if(!target)return false;const run=++generation.current;setLoading(true);setReadError('');const unreadable:string[]=[];
  try{const [g,cs]=await Promise.all([readGroup(connection,target,minContextSlot),readCommitments(connection,target,minContextSlot,a=>unreadable.push(a))]);
   if(generation.current!==run)return false;selectGroup(target);setGroup(g);setGroups(previous=>[g,...previous.filter(item=>item.address!==g.address)]);setCommitments(cs);setReadWarnings(unreadable);
   const metadata=await Promise.all(cs.map(async c=>{try{const r=await fetch(`/api/metadata?address=${c.address}`);return [c.address,r.ok?await r.json():{status:'unavailable'}] as const;}catch{return [c.address,{status:'unavailable'}] as const;}}));
   if(generation.current===run)setTerms(Object.fromEntries(metadata));return generation.current===run;
  }catch(e){if(generation.current===run)setReadError(e instanceof Error?e.message:'Could not read confirmed accounts');return false;}finally{if(generation.current===run)setLoading(false);}
 },[connection,selectGroup]);
 const discover=useCallback(async()=>{
  if(!config)return;const run=++generation.current;setLoading(true);setReadError('');
  try{const all=await readGroups(connection,config.mint);if(generation.current!==run)return;setGroups(all);
   const requested=new URL(window.location.href).searchParams.get('group'),mine=address?all.filter(g=>g.roster.includes(address)):[];
   const chosen=all.find(g=>g.address===requested&&(g.roster.includes(address||'')||!address))||mine.find(g=>g.address===activeRef.current)||mine.find(g=>g.founder===address)||mine[0]||(!address?all.find(g=>g.address===groupAddress):undefined);
   if(chosen)await reload(undefined,chosen.address);else{activeRef.current='';setActiveGroup('');setGroup(null);setCommitments([]);setTerms({});setReadWarnings([]);}
  }catch(e){if(generation.current===run)setReadError(e instanceof Error?e.message:'Could not find your groups');}finally{if(generation.current===run)setLoading(false);}
 },[connection,config,address,reload]);
 useEffect(()=>{let current=true;void fetch('/api/demo-config').then(async response=>{const value=await response.json();if(!response.ok)throw Error(value.error);if(current)setConfig(value);}).catch(e=>{if(current)setError(e instanceof Error?e.message:'Demo configuration unavailable');});return()=>{current=false;};},[]);
 useEffect(()=>{setCreation(false);setGroupCreation(false);setSelected(null);void discover();return()=>{generation.current++;};},[discover]);
 useEffect(()=>{const timer=setInterval(()=>{setNow(Math.floor(Date.now()/1000));if(!busyRef.current){if(activeRef.current)void reload();else void discover();}},15000);return()=>clearInterval(timer);},[reload,discover]);
 async function transact(build:()=>Promise<Transaction>,target?:string,confirmationMessage?:string){
  if(busyRef.current)throw new Error('A transaction is already in progress');busyRef.current=true;setBusy(true);setError('');setNotice('');setSignature('');setRefundSignature('');setPhase(null);const initial=contextRef.current,originalWallet=wallet.publicKey?.toBase58();
  try{const tx=await build();if(contextRef.current!==initial)throw new Error('Wallet or group changed');const result=await sendAndConfirm(tx,wallet,connection,{context:()=>contextRef.current,onPhase:(p,s)=>{setPhase(p);if(s)setSignature(s);}});
   if(walletRef.current.publicKey?.toBase58()!==originalWallet){setNotice('Transaction confirmed for the previous wallet. Review its receipt.');return result;}
   const refreshed=await reload(result.confirmedSlot,target||activeRef.current);setNotice(refreshed?(confirmationMessage||'Transaction confirmed. Showing the latest chain state.'):'Transaction confirmed. Refresh before acting again.');return result;
  }catch(e){setError(e instanceof Error?e.message:'Transaction failed');throw e;}finally{busyRef.current=false;setBusy(false);}
 }
 async function getDemoFunds(){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setNotice('Sign a message to claim demo tokens and Devnet SOL.');try{const result=await claimDemoFunds(wallet,()=>contextRef.current);setNotice('Demo funding confirmed. Your wallet can now create a group and stake test tokens.');if(result.signature)setSignature(result.signature);}catch(e){setError(e instanceof Error?e.message:'Demo funding unavailable');}finally{busyRef.current=false;setBusy(false);}}
 async function createGroup(setup:PreparedGroup){
  if(!address||busyRef.current)return;busyRef.current=true;setBusy(true);setError('');const initial=contextRef.current;
  try{if(await connection.getAccountInfo(groupPda(address),'confirmed'))throw new Error('This wallet already owns a group. Choose it from your groups.');
   const ata=getAssociatedTokenAddressSync(new PublicKey(setup.mint),new PublicKey(address));let tokens=0n;if(await connection.getAccountInfo(ata))tokens=(await getAccount(connection,ata)).amount;
   const sol=await connection.getBalance(new PublicKey(address));
   if(config?.fundingEnabled&&(tokens<1_000_000n||sol<10_000_000)){busyRef.current=true;setBusy(true);setNotice('Sign a message to receive demo tokens and Devnet SOL before creating your group.');await claimDemoFunds(wallet,()=>contextRef.current);busyRef.current=false;setBusy(false);}
   if(contextRef.current!==initial)throw new Error('Wallet changed. Review the group again.');
   busyRef.current=false;await transact(()=>initializeGroupAction(connection,setup,address),groupPda(address).toBase58());setGroupCreation(false);setNotice('Group created on Devnet. Copy the invitation link and share it with your invited members.');
  }catch(e){setError(e instanceof Error?e.message:'Group creation failed');}finally{busyRef.current=false;setBusy(false);}
 }
 async function create(draft:CommitmentDraft){if(!group)return;const random=new Uint32Array(2);crypto.getRandomValues(random);const nonce=(BigInt(random[0])<<32n)|BigInt(random[1]);let createdAddress='';try{await transact(async()=>{const built=await createAction(connection,group,draft,nonce);createdAddress=built.address;return built.transaction;});setCreation(false);setSelected(createdAddress);const record={address:createdAddress,terms:draft};setOutbox(record);await saveTerms(record);}catch{}}
 async function saveTerms(record:{address:string;terms:CommitmentDraft}){try{const r=await fetch('/api/metadata',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});const value=await r.json();if(!r.ok)throw new Error(value.error);setOutbox(null);await reload();}catch(e){setNotice(`The commitment is onchain. Terms could not be saved: ${e instanceof Error?e.message:'storage unavailable'}. Export them and retry saving.`);}}
 const requestRefund=useCallback(async(refundAddress:string,visible=true)=>{
  if(refundRequests.current.has(refundAddress))return;refundRequests.current.add(refundAddress);const initial=contextRef.current;if(visible)setNotice('Approval recorded. Returning the stake to its owner…');
  try{const response=await fetch('/api/refund',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:refundAddress})});const result=await response.json();if(contextRef.current!==initial)return;if(!response.ok)throw Error(result.error);if(result.signature)setRefundSignature(result.signature);
   if(result.status==='paid'){await reload();if(visible)setNotice('Refund confirmed. The stake has been returned to its owner.');}
   else if(visible)setNotice(result.status==='not-ready'?'Approval recorded. Waiting for the remaining appointed reviewers.':'Approval recorded. Refund delivery is pending; the service will retry. Your entitlement remains onchain.');
  }catch{if(visible&&contextRef.current===initial)setNotice('Approval recorded. Automatic refund is unavailable; the entitlement remains available to retry.');}finally{refundRequests.current.delete(refundAddress);}
 },[reload]);
 const pendingRefundKey=commitments.filter(c=>['succeeded','unresolved'].includes(c.status)&&!c.refundReleased).map(c=>c.address).join(',');
 useEffect(()=>{if(!pendingRefundKey)return;for(const key of pendingRefundKey.split(',').slice(0,5))void requestRefund(key,false);},[pendingRefundKey,requestRefund]);
 async function act(c:CommitmentView,a:LifecycleAction){if(!group||!address)return;try{await transact(()=>lifecycleAction(connection,group,c,address,a),undefined,a==='activate'?`Stake locked: ${formatTokenAmount(c.amount,group.decimals)} test tokens. ${c.mode==='github'?'Automated verification is pending.':'Awaiting completion approval from your reviewer'+(c.mode==='multiple'?'s':c.mode==='group'?' group':'')+'.'} Your stake stays in escrow until the outcome is recorded.`:undefined);if(a==='approve'||a==='resolveUnverified')await requestRefund(c.address);}catch{}}
 async function spend(event:React.FormEvent){event.preventDefault();if(!group||!address)return;try{const amount=parseTokenAmount(withdraw,group.decimals);if(amount<=0n||amount>group.pool)throw new Error('Choose an amount within the available communal budget');await transact(()=>withdrawAction(connection,group,address,amount));setWithdraw('');}catch(e){setError(e instanceof Error?e.message:'Withdrawal failed');}}
 async function shareGroup(){if(!group)return;const url=new URL(window.location.href);url.searchParams.set('group',group.address);try{await navigator.clipboard.writeText(url.toString());setNotice('Invitation link copied. Send it to the wallet addresses in your group.');}catch{setNotice(`Invitation link: ${url.toString()}`);}}
 function exportCreConfig(){if(!group)return;const data={mode:'staging',schedule:'*/30 * * * * *',chainSelector:'16423721717087811551',rpcUrl:connection.rpcEndpoint,receiverProgramId:'A2JT4HUJYEd3BL5xPXRiaXjvoFSMetY8zvLEPmRAxXPf',group:group.address,forwarderProgramId:group.policy.forwarder.toBase58(),forwarderState:group.policy.forwarderState.toBase58(),candidateAddresses:commitments.filter(c=>c.status==='active'||(['succeeded','unresolved'].includes(c.status)&&!c.refundReleased)).slice(0,25).map(c=>c.address)};if(!data.candidateAddresses.length){setNotice('Create and activate a commitment before exporting CRE configuration.');return;}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='config.demo.json';a.click();URL.revokeObjectURL(url);}
 const detail=commitments.find(c=>c.address===selected),member=!!address&&!!group?.roster.includes(address),ownsGroup=!!address&&groups.some(g=>g.founder===address);
 const own=commitments.filter(c=>c.owner===address),active=own.filter(c=>c.status==='active').reduce((s,c)=>s+c.amount,0n),refundable=own.filter(c=>['succeeded','unresolved'].includes(c.status)&&!c.refundReleased).reduce((s,c)=>s+c.amount,0n);
 const reviews=commitments.filter(c=>group&&needsReview(c,group,address,now)),visible=tab==='reviews'?reviews:refundsOnly?own.filter(c=>['succeeded','unresolved'].includes(c.status)&&!c.refundReleased):own;
 function navigate(section:Section){setTab(section);setCreation(false);setGroupCreation(false);setSelected(null);setRefundsOnly(false);}
 function openCommitment(id:string){setSelected(id);setCreation(false);window.scrollTo({top:0,behavior:'smooth'});}
 const amount=(n:bigint)=>formatTokenAmount(n,group?.decimals??6);
 const rows:CommitmentRowData[]=visible.map(c=>{const d=terms[c.address],hasTerms=d?.status==='verified'&&!!d.terms,actions=group?availableActions(c,group,address,now):[],expired=c.status==='active'&&c.mode!=='github'&&now>c.reviewDeadline,refundable=['succeeded','unresolved'].includes(c.status)&&!c.refundReleased;
  return {id:c.address,goal:hasTerms?d.terms!.goal:'Terms unavailable',summary:hasTerms?`${amount(c.amount)} test tokens · ${c.status==='active'?`${c.mode==='github'?'Due':'Review by'} ${displayTime(c.mode==='github'?c.goalDeadline:c.reviewDeadline)} SGT`:c.owner===address?'Your commitment':short(c.owner)}`:`${amount(c.amount)} test tokens · Original terms need verification.`,status:commitmentStatus(c,now),tone:expired||c.status==='failed'?'attention':c.status==='succeeded'?'success':c.status==='active'&&c.mode!=='github'?'pending':'neutral',action:actions.includes('acknowledge')?'Review invitation':actions.includes('activate')?'Lock stake':actions.includes('approve')?'Review evidence':refundable?'Refund status':undefined};
 });
 const focused=groupCreation||!!(creation&&group&&address)||!!detail;
 return <main className="shell"><PactHeader section={tab} onNavigate={navigate} reviewCount={reviews.length} wallet={<WalletButton/>}/>
 {!focused?<><section className="hero"><div><p className="eyebrow">YOUR ACCOUNTABILITY CIRCLE</p><h1>{tab==='reviews'?'A little follow-through.':tab==='pool'?'Our shared pool.':'Keep your word.'}</h1></div>{tab==='commitments'&&member?<button disabled={busy} onClick={()=>{setCreation(true);setSelected(null);}}>+ Make a commitment</button>:null}</section>
 {address?<div className="group-toolbar">{groups.filter(g=>g.roster.includes(address)).length?<SelectField label="Your group" value={activeGroup} disabled={busy} onChange={value=>{setSelected(null);void reload(undefined,value);}} options={groups.filter(g=>g.roster.includes(address)).map(g=>({value:g.address,label:`${g.founder===address?'Your circle':`${short(g.founder)}’s circle`} · ${g.roster.length} members`}))}/>:<p className="muted">Create a circle or open an invitation from a friend.</p>}<div className="button-row">{!ownsGroup&&config?<button className="quiet" disabled={busy||loading} onClick={()=>setGroupCreation(true)}>+ Create a group</button>:null}{group?<button className="quiet" onClick={shareGroup}>Copy invitation link</button>:null}{config?.fundingEnabled?<button className="text-button" disabled={busy} onClick={getDemoFunds}>Get demo tokens</button>:null}</div></div>:null}
 {tab==='commitments'&&group?<BalanceSummary active={address&&!readWarnings.length?amount(active):'—'} refundable={address&&!readWarnings.length?amount(refundable):'—'} pool={amount(group.pool)} onPool={()=>navigate('pool')} onRefunds={()=>setRefundsOnly(true)}/>:null}</>:null}
 {group?.policy.forwarder.toBase58()==='7kuEAA3mSC1Tz8gQjnvH7bKFda9xSPRRin9SZbH49cNK'?<p className="notice">Devnet demo · Local CRE simulation · Mock forwarder</p>:null}
 {readError?<p className="notice" role="alert">{readError}</p>:null}
 {readWarnings.length?<section className="notice" role="status"><strong>Some commitment records are unavailable</strong><p>Wallet totals may be incomplete. Inspect the affected accounts:</p>{readWarnings.map(key=><a key={key} className="member" href={accountLink(key)} target="_blank" rel="noreferrer">{short(key)} ↗</a>)}</section>:null}
 {phase||notice||error?<section className={`transaction-notice ${error?'has-error':''}`} aria-live="polite"><strong>{phase?phase.charAt(0).toUpperCase()+phase.slice(1):error?'Action needs attention':'Update'}</strong>{notice?<p>{notice}</p>:null}{error?<p>{error}</p>:null}{signature?<a href={`https://explorer.solana.com/tx/${signature}?cluster=devnet`} target="_blank" rel="noreferrer">View transaction receipt ↗</a>:null}{refundSignature?<p><a href={`https://explorer.solana.com/tx/${refundSignature}?cluster=devnet`} target="_blank" rel="noreferrer">View refund receipt ↗</a></p>:null}{phase==='failed'&&signature?<p>Check the receipt before retrying; confirmation may be unavailable.</p>:null}</section>:null}
 {outbox?<section className="notice"><strong>Save your original terms</strong><p>The chain transaction succeeded. Keep an export while storage is retried.</p><div className="button-row"><button className="quiet" onClick={()=>exportTerms(outbox.terms,outbox.address)}>Export terms ↓</button><button disabled={busy} onClick={()=>saveTerms(outbox)}>Retry metadata save</button></div></section>:null}
 {groupCreation&&address&&config?<GroupForm key={address} owner={address} config={config} busy={busy} onCreate={createGroup} onClose={()=>setGroupCreation(false)}/>:null}
 {creation&&group&&address?<CreateForm key={address} group={group} owner={address} busy={busy} onCreate={create} onClose={()=>setCreation(false)}/>:null}
 {detail&&group?<Detail key={detail.address} commitment={detail} group={group} walletAddress={address} busy={busy} now={now} onAction={act} onClose={()=>setSelected(null)}/>:null}
 {!focused&&tab!=='pool'?<section className="commitments" aria-label={tab==='reviews'?'Reviews':'Your commitments'}><div className="list-tools">{refundsOnly?<button className="text-button" onClick={()=>setRefundsOnly(false)}>← All commitments</button>:<span/>}<button className="text-button refresh" disabled={loading||busy} onClick={()=>activeRef.current?reload():discover()}>{loading?'Refreshing…':'Refresh'}</button></div>
 {loading&&!group?<p className="empty" role="status">Finding your circle…</p>:!address?<div className="empty"><h2>Make yourself at home.</h2><p>Connect your wallet to create a group, invite friends and make your first commitment.</p></div>:!group?<div className="empty"><h2>Accountability starts with your people.</h2><p>Create a group and invite their wallet addresses. We’ll help you get test tokens and Devnet SOL.</p>{config&&!ownsGroup?<button disabled={busy||loading} onClick={()=>setGroupCreation(true)}>Create your group →</button>:null}</div>:visible.length?<CommitmentList rows={rows} busy={busy} onOpen={openCommitment} onAction={openCommitment}/>:<div className="empty"><h2>{tab==='reviews'?'You’re all caught up.':refundsOnly?'No refunds waiting.':'Your next promise starts here.'}</h2><p>{tab==='reviews'?'Reviewer invitations and completion reviews will appear here.':refundsOnly?'Refunds are returned automatically after final approval.':'A clear goal is a good place to start.'}</p></div>}</section>:null}
 {!focused&&tab==='pool'?<section className="pool-view"><div className="pool-heading"><img src="/ripple-mark.png" alt="" width="58" height="58"/><div><p className="eyebrow">AVAILABLE TO THE GROUP</p><h2>{group?amount(group.pool):'—'} <span>test tokens</span></h2></div></div><p className="muted">Forfeited stakes support the circle. Locked stakes and unpaid refunds stay separate.</p><details className="group-activity"><summary>Group commitments · {commitments.length}</summary><ul className="activity-list">{commitments.map(c=><li key={c.address}><button className="text-button" onClick={()=>openCommitment(c.address)}>{terms[c.address]?.status==='verified'?terms[c.address].terms?.goal:'Terms unavailable'}</button><span>{short(c.owner)}</span></li>)}</ul></details></section>:null}
 {!focused&&tab==='pool'&&group?<details className="panel group-details"><summary>Group rules & public accounts</summary><p>A fixed roster and shared test mint. Each group has its own escrow vault and accounting.</p><p>{group.roster.map(r=><a key={r} className="member" href={accountLink(r)} target="_blank" rel="noreferrer">{short(r)}{r===group.treasurer?' · treasurer':''}</a>)}</p><div className="button-row"><a href={accountLink(group.mint)} target="_blank" rel="noreferrer">Test mint ↗</a><a href={accountLink(group.vault)} target="_blank" rel="noreferrer">Escrow vault ↗</a><a href={accountLink(group.address)} target="_blank" rel="noreferrer">Group account ↗</a><button className="text-button" onClick={exportCreConfig}>Export CRE configuration</button></div>{group.treasurer===address?<form onSubmit={spend}><label>Spend available communal budget · test tokens<input value={withdraw} onChange={e=>setWithdraw(e.target.value)} inputMode="decimal" required/></label><p className="muted">Destination is fixed: {short(group.treasuryRecipient)}. Active escrow and unpaid refunds remain protected.</p><button disabled={busy||group.pool===0n}>Withdraw to fixed treasury recipient</button></form>:null}</details>:null}
 <PactFooter/></main>;
}
