'use client';
import {useEffect,useRef,useState} from 'react';
import {sha256} from '@noble/hashes/sha256';
import {Buffer} from 'buffer';
import {useWallet} from '@solana/wallet-adapter-react';
import {displayTime} from '../../../packages/shared/src/time';
import {formatTokenAmount} from '../../../packages/shared/src/amount';
import type {CommitmentDraft} from '../../../packages/shared/src/schema';
import {availableActions,type LifecycleAction} from '../lib/actions';
import type {GroupView,CommitmentView} from '../lib/chain';
import {commitmentStatus} from '../lib/presentation';
import {modeLabels} from './create-form';
const actionLabel:Record<LifecycleAction,string>={acknowledge:'Accept reviewer role',activate:'Lock stake & activate',approve:'Approve completion',settleExpired:'Process expired commitment',resolveUnverified:'Record unresolved refund',releaseRefund:'Retry refund manually'};
export const short=(key:string)=>`${key.slice(0,6)}…${key.slice(-4)}`;
export const accountLink=(key:string)=>`https://explorer.solana.com/address/${key}?cluster=devnet`;
export function exportTerms(terms:CommitmentDraft,address:string){const url=URL.createObjectURL(new Blob([JSON.stringify({commitment:address,terms},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`vowpool-${address}.json`;a.click();URL.revokeObjectURL(url);}
export default function Detail({commitment:c,group,walletAddress,busy,now,onAction,onClose}:{commitment:CommitmentView;group:GroupView;walletAddress?:string;busy:boolean;now:number;onAction:(c:CommitmentView,a:LifecycleAction)=>Promise<void>;onClose:()=>void}){
 const wallet=useWallet(),walletRef=useRef(wallet);walletRef.current=wallet;const [metadata,setMetadata]=useState<{status:string;terms?:CommitmentDraft}>({status:'loading'}),[evidence,setEvidence]=useState<Array<{note:string;url?:string;created:number}>>([]),[note,setNote]=useState(''),[url,setUrl]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{let current=true;setMetadata({status:'loading'});setEvidence([]);void Promise.all([fetch(`/api/metadata?address=${c.address}`).then(r=>r.json()),fetch(`/api/evidence?address=${c.address}`).then(r=>r.json())]).then(([m,e])=>{if(current){setMetadata(m.error?{status:'unavailable'}:m);setEvidence(e.evidence||[]);}}).catch(()=>{if(current)setMetadata({status:'unavailable'});});return()=>{current=false;};},[c.address,c.termsHash]);
 async function publish(event:React.FormEvent){event.preventDefault();if(saving||!wallet.signMessage)return;setSaving(true);setMessage('Requesting evidence signature…');try{const content={note,...(url?{url}:{})};const hash=Buffer.from(sha256(new TextEncoder().encode(JSON.stringify({note,url:url||null})))).toString('hex');const challengeResponse=await fetch(`/api/challenge?address=${c.address}&contentHash=${hash}`);const challenge=await challengeResponse.json();if(!challengeResponse.ok)throw new Error(challenge.error);const original=wallet.publicKey?.toBase58();if(original!==c.owner)throw new Error('Connect the commitment owner');const signature=await wallet.signMessage(new TextEncoder().encode(challenge.message));if(walletRef.current.publicKey?.toBase58()!==original)throw new Error('Wallet changed. Request a new challenge.');const response=await fetch('/api/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:c.address,evidence:content,id:challenge.id,signature:Buffer.from(signature).toString('base64')})});const result=await response.json();if(!response.ok)throw new Error(result.error);setNote('');setUrl('');setMessage('Signed evidence saved. Completion approval remains a separate action.');setEvidence((await (await fetch(`/api/evidence?address=${c.address}`)).json()).evidence||[]);}catch(e){setMessage(e instanceof Error?e.message:'Evidence could not be saved');}finally{setSaving(false);}}
 const actions=availableActions(c,group,walletAddress,now),terms=metadata.status==='verified'?metadata.terms:undefined;
 return <section className="panel detail" aria-label="Commitment detail"><div className="section-head"><div><p className="eyebrow">FROZEN COMMITMENT</p><h1>{terms?.goal||'Commitment terms unavailable'}</h1></div><button className="quiet" onClick={onClose}>Close</button></div><div className="badges"><span className={`status ${c.status}`}>{commitmentStatus(c,now)}</span><span className="tag">{modeLabels[c.mode]}</span></div>
 {terms?<><p>{terms.criteria}</p>{terms.consequence?<p className="muted">Physical consequence: {terms.consequence}</p>:null}<button className="text-button" onClick={()=>exportTerms(terms,c.address)}>Export original terms ↓</button></>:<p className="notice">Terms are {metadata.status}. The chain record still controls funds and permissions. Verify the original exported terms before acknowledging or approving.</p>}
 <dl className="facts"><div><dt>Owner</dt><dd><a href={accountLink(c.owner)} target="_blank" rel="noreferrer">{short(c.owner)}</a></dd></div><div><dt>Stake</dt><dd>{formatTokenAmount(c.amount,group.decimals)} test tokens</dd></div><div><dt>Goal deadline</dt><dd>{displayTime(c.goalDeadline)} SGT</dd></div><div><dt>Review cutoff</dt><dd>{displayTime(c.reviewDeadline)} SGT</dd></div><div><dt>Activated</dt><dd>{c.activatedAt?displayTime(c.activatedAt)+' SGT':'Awaiting activation'}</dd></div><div><dt>Refund</dt><dd>{c.refundReleased?'Paid to owner':['succeeded','unresolved'].includes(c.status)?'Recorded · awaiting payout':'No entitlement recorded'}</dd></div></dl>
 {c.status==='active'?<p className="notice"><strong>Stake locked: {formatTokenAmount(c.amount,group.decimals)} test tokens.</strong> {c.mode==='github'?'Awaiting automated verification.':now>c.reviewDeadline?'The review cutoff has passed. Expiry processing will move this stake to the communal pool.':'Awaiting completion approval. Approval by the review cutoff makes your stake refundable; missing approval sends it to the communal pool.'}</p>:null}
 {c.github?<div className="notice"><a href={`https://github.com/${c.github.owner}/${c.github.repo}/pull/${c.github.pr}`} target="_blank" rel="noreferrer">{c.github.owner}/{c.github.repo} · PR #{c.github.pr}</a><p>Exact target branch: <strong>{c.github.targetBranch}</strong>. Merge must occur after activation and by the goal deadline.</p><p>Unresolved resolution opens after {displayTime(c.hardDeadline)} SGT. Unknown evidence is retried; human approval is unavailable.</p>{c.observedAt?<small>Last accepted observation: {displayTime(c.observedAt)} SGT{c.mergedAt?` · merged ${displayTime(c.mergedAt)} SGT`:''}</small>:null}</div>:<><h3>Reviewers</h3>{c.reviewers.length?<ul className="reviewers">{c.reviewers.map((r,i)=><li key={r}><span>{short(r)}</span><span>{(c.acknowledgments>>i)&1?'Role accepted':'Role pending'}</span><span>{(c.approvals>>i)&1?'Approved':'Not approved'}</span></li>)}</ul>:<p className="muted">Any eligible group member other than the owner may approve. The first recorded approval completes the commitment.</p>}</>}
 {['succeeded','unresolved'].includes(c.status)&&!c.refundReleased?<p className="notice">Your refund is recorded onchain. The demo service returns it automatically; if delivery is unavailable, it remains safe to retry.</p>:null}
 <div className="button-row">{actions.filter(a=>a!=='releaseRefund').map(a=><button key={a} disabled={busy||(['acknowledge','approve'].includes(a)&&!terms)} onClick={()=>onAction(c,a)}>{actionLabel[a]}</button>)}</div>
 {actions.includes('releaseRefund')?<details><summary>Refund recovery</summary><p>Use this fallback if the automatic service is unavailable. It can only pay the recorded owner.</p><button className="quiet" disabled={busy} onClick={()=>onAction(c,'releaseRefund')}>Retry refund manually</button></details>:null}
 <h3>Evidence</h3>{evidence.length?evidence.map((e,i)=><article className="evidence" key={i}><p>{e.note}</p>{e.url?<a href={e.url} target="_blank" rel="noreferrer">Open evidence ↗</a>:null}<small>{displayTime(e.created)} SGT · owner-signed</small></article>):<p className="muted">No signed evidence has been published.</p>}
 {walletAddress===c.owner?<form onSubmit={publish}><label>Evidence note<textarea required value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></label><label>HTTPS evidence link · optional<input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button className="quiet" disabled={saving||busy||!wallet.signMessage}>{saving?'Saving…':'Sign & publish evidence'}</button>{!wallet.signMessage?<small>This wallet does not support message signing.</small>:null}</form>:null}{message?<p role="status" className="notice">{message}</p>:null}
 <details><summary>Chain record</summary><p><a href={accountLink(c.address)} target="_blank" rel="noreferrer">View commitment on Solana Devnet ↗</a></p><p className="hash">Terms hash: {c.termsHash}</p><p className="hash">Config hash: {c.configHash}</p></details></section>;
}
