'use client';
import {useRef,useState} from 'react';
import SelectField from './select-field';
import {makeGroupSetup} from '../lib/groups';
import {addInvitations} from '../lib/invitation-input';
import {preparedGroup} from '../lib/chain';
import type {PreparedGroup} from '../../../packages/shared/src/group-setup';
import {short} from './detail';
export type DemoConfig={mint:string;policy:PreparedGroup['policy'];developmentFixture:boolean;fundingEnabled:boolean};
export default function GroupForm({owner,config,busy,onCreate,onClose}:{owner:string;config:DemoConfig;busy:boolean;onCreate:(setup:PreparedGroup)=>Promise<void>;onClose:()=>void}){
 const prepared=preparedGroup?.founder===owner?preparedGroup:null;
 const [invited,setInvited]=useState<string[]>(prepared?.roster.filter(a=>a!==owner)||[]),[draft,setDraft]=useState(''),[treasurer,setTreasurer]=useState(prepared?.treasurer||owner),[error,setError]=useState(''),[review,setReview]=useState<PreparedGroup|null>(null);
 const input=useRef<HTMLInputElement>(null),roster=[owner,...invited];
 function add(text=draft){const result=addInvitations(invited,text,owner);setInvited(result.addresses);setDraft(result.remaining);setError(result.error);return result;}
 function remove(address:string){setInvited(current=>current.filter(a=>a!==address));if(treasurer===address)setTreasurer(owner);setError('');input.current?.focus();}
 function confirm(event:React.FormEvent){event.preventDefault();const result=add();if(result.remaining){input.current?.focus();return;}if(!result.addresses.length){setError('Invite at least one other wallet to create your circle.');input.current?.focus();return;}try{setReview(makeGroupSetup(owner,result.addresses,treasurer,config.mint,config.policy));setError('');}catch(e){setError(e instanceof Error?e.message:'Check the invited wallet addresses');}}
 return <section className="panel creation" aria-label="Create accountability group"><div className="section-head"><div><p className="eyebrow">BRING YOUR PEOPLE</p><h1>Create your circle.</h1></div><button className="quiet" disabled={busy} onClick={onClose}>Close</button></div>
 {review?<><h3>Review your group</h3><p>You create and sign for this group as <strong>{short(owner)}</strong>.</p><ul className="reviewers">{review.roster.map(a=><li key={a}>{short(a)}{a===owner?' · you':''}{a===review.treasurer?' · treasurer':''}</li>)}</ul><p>The treasurer can withdraw forfeited funds only to their own frozen wallet address. Active stakes and unpaid refunds remain protected.</p><p className="notice">The roster and treasury destination are fixed after creation. Invited members connect their own wallets using your group link.</p><div className="button-row"><button className="quiet" disabled={busy} onClick={()=>setReview(null)}>Edit group</button><button disabled={busy} onClick={()=>onCreate(review)}>{busy?'Preparing your group…':'Create group'}</button></div></>:<form onSubmit={confirm}><p>Invite 1–7 people by their public Solana wallet address. Your wallet is included automatically.</p>
 <div className="invitation-field"><div className="invitation-heading"><label htmlFor="invited-wallets">Invited wallet addresses</label><span aria-live="polite">{invited.length}/7 invited</span></div>
 <div className="wallet-input" onClick={()=>input.current?.focus()}>
 {invited.map(address=><span className="wallet-pill" key={address}><span title={address}>{address}</span><button type="button" disabled={busy} aria-label={`Remove ${address}`} onClick={event=>{event.stopPropagation();remove(address);}}>×</button></span>)}
 <input id="invited-wallets" ref={input} value={draft} disabled={busy} autoComplete="off" autoCapitalize="none" spellCheck={false} aria-describedby={`invitation-hint${error?' invitation-error':''}`} aria-invalid={!!error} placeholder={invited.length?'Add another wallet address':'Type or paste wallet addresses'} onChange={event=>{const value=event.target.value;if(/[\s,]/.test(value)&&!(event.nativeEvent as InputEvent).isComposing){const lastSeparator=Math.max(value.lastIndexOf(','),...Array.from(value.matchAll(/\s/g),match=>match.index!));const result=add(value.slice(0,lastSeparator+1));setDraft([result.remaining,value.slice(lastSeparator+1)].filter(Boolean).join(' '));}else{setDraft(value);setError('');}}} onKeyDown={event=>{if(event.nativeEvent.isComposing)return;if(['Enter',',',' '].includes(event.key)){event.preventDefault();add();}}} onPaste={event=>{const text=event.clipboardData.getData('text');if(/[\s,]/.test(text)){event.preventDefault();const field=event.currentTarget;add(draft.slice(0,field.selectionStart??draft.length)+text+draft.slice(field.selectionEnd??draft.length));}}} onBlur={()=>{if(draft.trim())add();}}/>
 </div><p id="invitation-hint" className="invitation-hint">Press comma, Enter, or space to add a wallet. You can also paste a list separated by commas or new lines.</p>{error?<p id="invitation-error" className="error" role="alert">{error}</p>:null}</div>
 <SelectField label="Treasurer" disabled={busy} value={treasurer} onChange={setTreasurer} options={roster.map(address=>({value:address,label:address===owner?'You':short(address),description:address}))}/><p className="muted">The treasurer receives communal withdrawals. Each commitment owner receives their own refund.</p><button disabled={busy}>Review group →</button></form>}
 <small>Solana Devnet · Custom test tokens · One group per founder wallet. CRE checks use local simulation.</small></section>;
}
