import {it,expect,vi} from 'vitest';
import {Keypair,Transaction,SystemProgram} from '@solana/web3.js';
import {sendAndConfirm} from '../lib/transactions';
import {DEVNET_GENESIS} from '../lib/chain';
const owner=Keypair.generate();
const tx=()=>new Transaction().add(SystemProgram.transfer({fromPubkey:owner.publicKey,toPubkey:owner.publicKey,lamports:0}));
function harness(){let context='a';const phases:string[]=[];const connection:any={getGenesisHash:vi.fn(async()=>DEVNET_GENESIS),getLatestBlockhash:vi.fn(async()=>({blockhash:Keypair.generate().publicKey.toBase58(),lastValidBlockHeight:100})),sendRawTransaction:vi.fn(async()=>'signature'),confirmTransaction:vi.fn(async()=>({context:{slot:10},value:{err:null}}))};const wallet:any={publicKey:owner.publicKey,signTransaction:vi.fn(async(t:Transaction)=>{t.partialSign(owner);return t;})};return {connection,wallet,phases,getContext:()=>context,change:()=>{context='b';}};}
it('emits confirmed only after confirmation succeeds',async()=>{const h=harness();const result=await sendAndConfirm(tx(),h.wallet,h.connection,{context:h.getContext,onPhase:p=>h.phases.push(p)});expect(h.phases).toEqual(['signature requested','submitted','confirmed']);expect(result).toEqual({signature:'signature',confirmedSlot:10});});
it('rejected signature never submits or confirms',async()=>{const h=harness();h.wallet.signTransaction.mockRejectedValue(new Error('Rejected'));await expect(sendAndConfirm(tx(),h.wallet,h.connection,{context:h.getContext,onPhase:p=>h.phases.push(p)})).rejects.toThrow('Rejected');expect(h.connection.sendRawTransaction).not.toHaveBeenCalled();expect(h.phases).not.toContain('confirmed');});
it('failed confirmation never claims success',async()=>{const h=harness();h.connection.confirmTransaction.mockResolvedValue({context:{slot:1},value:{err:{InstructionError:[0,'error']}}});await expect(sendAndConfirm(tx(),h.wallet,h.connection,{context:h.getContext,onPhase:p=>h.phases.push(p)})).rejects.toThrow('Transaction failed');expect(h.phases).not.toContain('confirmed');});
it('wallet/network change during signature aborts submission',async()=>{const h=harness();h.wallet.signTransaction.mockImplementation(async(t:Transaction)=>{t.partialSign(owner);h.change();return t;});await expect(sendAndConfirm(tx(),h.wallet,h.connection,{context:h.getContext})).rejects.toThrow('changed');expect(h.connection.sendRawTransaction).not.toHaveBeenCalled();});
it('refuses another cluster before signature',async()=>{const h=harness();h.connection.getGenesisHash.mockResolvedValue('mainnet');await expect(sendAndConfirm(tx(),h.wallet,h.connection,{context:h.getContext})).rejects.toThrow('Devnet');expect(h.wallet.signTransaction).not.toHaveBeenCalled();});
it('checks cluster again before sending signed transaction',async()=>{const h=harness();h.connection.getGenesisHash.mockResolvedValueOnce(DEVNET_GENESIS).mockResolvedValueOnce('mainnet');await expect(sendAndConfirm(tx(),h.wallet,h.connection,{context:h.getContext})).rejects.toThrow('Devnet');expect(h.connection.sendRawTransaction).not.toHaveBeenCalled();});
